# Backtest configs for the 28 "zero-shot" datasets.
# These datasets were not seen by Chronos models during training.
- name: default
  hf_repo: '/home/ubuntu/timeseries-modeling/data/bike_day_q4'
  offset: -91
  prediction_length: 91
  num_rolls: 1
  segment_name: 'q4'
